//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicacion_ASP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int Pk_Empleado { get; set; }
        public string Nombre { get; set; }
        public string Ape_Paterno { get; set; }
        public string APe_Materno { get; set; }
        public Nullable<int> Edad { get; set; }
        public Nullable<int> Telefono { get; set; }
    }
}
